version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./backend:/accubalance/backend
      - ./frontend:/accubalance/frontend
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=accubalance
      - POSTGRES_USER=sajan
      - POSTGRES_PASSWORD=sajan
volumes:
  postgres_data:
